### ISSUE TITLE
App not starting in Nexus 5 with Android 6.0.1

### ISSUE THREAD

**Issue by alejandroscf** [richsmith/sexytopo#16]
Either the app from Google Play or Fdroid when opening it, it doesn't work and show an error saying "Unfortunately, Sexytopo has stopped".

My phone is a Nexus 5 from Google and runs Android 6.0.1.

Best regards, 
Alejandro

**Comment by richsmith** [comment]
Hi Alejandro

Thanks for the bug report.

Unfortunately haven't been able to replicate this with my Nexus 5. It may be a problem with your device? I haven't received any logs about such an error that may enable me to find out the problem. Perhaps you could set your device to report errors to Google? Otherwise I'm afraid I don't know how to investigate this further.

cheers
Rich

**Comment by richsmith** [comment]
I think I've worked out what has caused this based on a similar issue I've experienced. It should be fixed in the next release (hopefully within the next couple of weeks). I'm going to close this based on that assumption.

**Comment by alejandroscf** [comment]
I've tried to send you back logs or bug reports, but I couldn't. I also tried to build the app from sources, but I was unsuccessful. I hope it will work soon.

**Comment by alejandroscf** [comment]
I've found the cause of the app not opening, if the app has no permission to read storage it didn't starts. Maybe showing a warning message if it hasn't the right permissions may help.

Best regards,
Alejandro

**Comment by richsmith** [comment]
Thanks for the diagnosis. I'm looking into fixing it for the next version. It certainly shouldn't crash, whatever the permissions!

**Comment by richsmith** [comment]
I should have fixed this. For now all surveys will be saved/loaded to the app's private directory on the SD card whatever the version of Android. I'll release a new version over the next couple of days.
