### ISSUE TITLE
surveyed a cool alpine cave - Error: Attempt to invoke virtual methode

### ISSUE THREAD

**Issue by benedikthartmann** [richsmith/sexytopo#182]
Hello Rich,

we surveyed a cool alpine cave. But now we can not open it again in the sexytopo app. See the screenshot and the survey data attached,
![Screenshot_20220907-143358](https://user-images.githubusercontent.com/57807593/189212579-1dbb76c7-f11e-485d-a0be-bf3a385b1868.png)

Error: Attempt to invoke virtual methode 'vioid org.hwyl.seytopo.model.survey.Station.addOnwardLeg....
[griess.zip](https://github.com/richsmith/sexytopo/files/9530171/griess.zip)

Maybe you can help us. We tried a load of things, other android version, ...

**Comment by olly** [comment]
I took a look at your file, and I think I've managed to find the issue and fix it. Hopefully all of your data is still there. I've uploaded the fixed version.

[Griess.zip](https://github.com/richsmith/sexytopo/files/9535259/Griess.zip)

It would be helpful to further diagnose the underlying cause of this issue if you could:

 * Let us know whether these updated files work for you?
 * Which version of Android are you using?
 * Which device are you using, and how are you inputting data into the data table?
 * Do you remember if you manually updated Station 8 in the data table? Or through some other action?

---

The underlying issue was that Station 8, had its name set to `8\n` (the legs also reference their `destination` as `8\n`). I was able to replicate this by renaming the station in the data table, and when editing the name, press the "return" button before confirming the input with the "RENAME" button.

I'm not too familiar with Android conventions, but is it possible for the "RETURN" button to function as the "RENAME" confirmation button? That might be a way to solve the issue nicely, and provide for a nicer UX.

Regardless this should probably also be fixed at the data model layer. Perhaps:

* Adding restriction & validation to the Station name field.
* Introduce a station id (UUID?), and reference this in the data model, relegating the Station name to a purely human-readable text field. Although, this might introduce issues with exporting to the various supported formats.

**Comment by benedikthartmann** [comment]
Hey Olivery,

thanks a lot for your fast reply - and the correction of the data. It works now. 

It would have took us ages to find this problem.

We are using this android version:
- Android 9 Version 
on a Sony Experia Mobile Phone

To input the data we are using a DistoX with a modification from Beat Heeb (maybe you know this) It is somehow described here, but in German: https://www.hoehlenverein-blaubeuren.de/index.php/distox2-vermessung

We darkly remember that we renamed the station 8, maybe this caused the issues.

Thanks a lot once again!

Kind Regards

Benedikt

**Comment by olly** [comment]
Benedikt,

I'm glad that's working for you now. I think I managed to find out how the bug occurred and have a change open for review, which once merged & released should prevent this from happening again.

Happy Exploring!

**Comment by richsmith** [comment]
Closing this thanks to Olly's PR - will be fixed in the next release.

**Comment by benedikthartmann** [comment]
> Benedikt,
> 
> I'm glad that's working for you now. I think I managed to find out how the bug occurred and have a change open for review, which once merged & released should prevent this from happening again.
> 
> Happy Exploring!

Great! Thanks a lot.
