### ISSUE TITLE
Random and increasingly frequent hangs

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#88]
Tried using ST in a simulated real survey scenario for the first time over the weekend. And took the opportunity to start training a friend in the principles of paperless surveying (using ST v1.2.2).
My friend has a Samsung J2 with 8GB of storage and just under 500MB available.  At first ST worked fine, but after a while we got more and more hangs from ST.
I am using a Samsung S8 with about 30GB available, and rarely get it to hang.
We're putting it down to a device with inadequate storage, and are not too worried (at least I'm not cos mine works!), although it would be preferable to have ST handle the problem and fail gracefully.  Will be interesting to see if v1.2.3 makes any difference.
#86

**Comment by richsmith** [comment]
Think this may have been because ST briefly had an issue where rotating the device caused it to crash. I've also made some improvements to how it fails (now crashes early rather than hangs, stores the crash, uploads error when it has internet, restarts a bit more gracefully) so I'm going to close this.
