### ISSUE TITLE
Make number of measurements to make a station configurable

### ISSUE THREAD

**Issue by richsmith** [richsmith/sexytopo#92]
A few people have requested this: allow changing the number of required measurements to make a new station (e.g. to 2 or 4 for various reasons).

**Comment by CaverBruce** [comment]
I am a fan of 3 measurements to define a survey leg, in part because that is what the distoX2 is setup for (if you activate the triple shot feature) and I would never contemplate choosing another default.  I am not against allowing ST to have configuration settings to default to other measurement numbers (2, 3, 4 whatever).  However it happens at least once on every surveying trip that I only get 1 or 2 usable measurements, or I get say 5 that i want to average across a single survey leg.  Usually due to difficult surveying or communication conditions.  With PocketTopo it is easy to manually edit the from and to station number on the fly to achieve exactly that.  Currently i don't think it can easily be done, or done at all, with ST (but I am happy to stand corrected).  So if as part of this you are considering providing the ability to edit an entire survey line, including from and to stations, then I am all for it.
